services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - system_design
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3

  zookeeper:
    image: zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    networks:
      - system_design
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181"]
      interval: 30s
      timeout: 30s
      retries: 3

  app:
    image: fabianoflorentino/system_design:v0.0.2
    build:
      context: .
      dockerfile: build/Dockerfile
    networks:
      - system_design
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    healthcheck:
      test: ["CMD-SHELL", "ps aux |grep 'sleep' || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    env_file:
      - ./config/.env
    depends_on:
      redis:
        condition: service_healthy
      zookeeper:
        condition: service_healthy

networks:
  system_design:
    driver: bridge
